services:
  quantum:
    image: qiskit/qiskit-runtime
    command: bash -c "pip install fastapi uvicorn[standard] && uvicorn main:app --host 0.0.0.0 --port 3002"
    working_dir: /app/quantum
    volumes:
      - ./quantum:/app/quantum
    ports:
      - "3002:3002"
  sodium:
    image: node:16
    command: bash -c "npm install && npm run dev"
    working_dir: /app/sodium
    volumes:
      - ./sodium:/app/sodium
    ports:
      - "3001:3001"
  frontend:
    image: node:16
    command: bash -c "npm run dev"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
