services:
  quantum:
    image: qiskit/qiskit-runtime
    command: python main.py
    working_dir: /app/quantum
    volumes:
      - ./quantum:/app/quantum
  sodium:
    image: node:16
    command: bash -c "npm install && npm run dev"
    working_dir: /app/sodium
    volumes:
      - ./sodium:/app/sodium
